sudo: required
dist: trusty
language: scala
scala:
   - 2.11.8
   - 2.12.0-M5
   - 2.12.0-RC1
   - 2.12.0-RC2
env:
- JDK=oraclejdk8
- JDK=openjdk8
- JDK=oraclejdk7
- JDK=openjdk7
addons:
  # https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
  hosts:
    - scala-logging
  hostname: scala-logging
before_script:
  - jdk_switcher use $JDK
matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.0-M5
      env: JDK=oraclejdk7
    - scala: 2.12.0-M5
      env: JDK=openjdk7
    - scala: 2.12.0-RC1
      env: JDK=oraclejdk7
    - scala: 2.12.0-RC1
      env: JDK=openjdk7
    - scala: 2.12.0-RC2
      env: JDK=oraclejdk7
    - scala: 2.12.0-RC2
      env: JDK=openjdk7